### ISSUE TITLE
Firefox issues?

### ISSUE THREAD

**Issue by thaKnza** [anapnoe/sd-webui-ux#10]
I get this in the web console

" Go to the Firefox about:config page, then search and toggle layout. css.has-selector. enabled "

This flag doesn't exist and it's not clear if you mean "layout.css.has-selector" or what.

I've let this thing sit for awhile and nothing ever happened. It sometimes seems like it's doing something, like set stuff up, but ultimately doesn't seem to finish. I also get this error:

"[svelte-i18n] Message "undefined" has syntax error: A message must be provided as a String or AST."

Unsure if related.

**Comment by anapnoe** [comment]
![about_firefox](https://github.com/user-attachments/assets/c38ba7c8-a85c-402b-b1a2-67cde50005b4)

maybe this screenshot can help you
