### ISSUE TITLE
Various settings are always on their base default values and ignore user-saved defaults when starting up an instance

### ISSUE THREAD

**Issue by Vi3trice** [anapnoe/sd-webui-ux#14]
I don't have a full range of what's actually affected, but this does impact base settings.

Whenever you launch an instance, certain values like txt2img sampler and scheduler always get loaded into their base default values. Going into settings to save defaults in ui-config.json does show the difference in settings gets detected.

![UI-Defaults](https://github.com/user-attachments/assets/f8a62fea-84a8-47d7-9daa-33e8876201d8)

**Comment by anapnoe** [comment]
There should be no interference can you backup your config.json and try this again config.json will be recreated upon restart change some values and apply if you are using Forge it has different user defaults for SD, SDXL, FLUX you can find them in quicksettings

**Comment by Vi3trice** [comment]
I deleted it, let it create another one and then tried just changing a few things, and it just reverts back again. There's also the two empty values that show up no matter what.

![UI-Defaults-2](https://github.com/user-attachments/assets/4b513c62-10f2-4c3c-842c-1e505cc4a2c0)

Changing the user defaults does work as a workaround, but still an odd behavior.

**Comment by anapnoe** [comment]
can you disable all other extensions and enable them one by one to see if the issue persists?
![Untitled](https://github.com/user-attachments/assets/0afce7a4-7e51-4b40-9f04-06d0a57bc931)
