### ISSUE TITLE
Notification sound no longer goes off, and Tree view issue, and paid Workspace UI not working.

### ISSUE THREAD

**Issue by kyle215ps3** [anapnoe/sd-webui-ux#15]
**Notification sounds don't always work, mostly rarely.**
I have the notification. mp3 in the root directory and the setting turned on, but looks like it no longer plays when I use this UI.

**Lora Network Tree**
Another thing is when in tree view for LoRa networks(so far) and I select a directory, it doesn't load it up except expand the tree view no matter where I click.

**About the Workspace** V1 & V2 Beta

I am Rule34 Diffusion as mentioned on your membership page of Buy Me a Coffee.

Note: I am using the latest forge, but a branch reforge which is the same exact gradio version.

Issue: I just got the workspaces UI since I paid for a sub but after I unzip the folder and put it into the extension folder it doesn't show up.
and when I check to activate it it shows it's already checked. Any idea what I'm missing?
I tried even having both the free one and the workspace activated together but that also doesn't work.

![image](https://github.com/user-attachments/assets/bc7d38f4-f4d3-413c-9de0-c1d8c76f63bc)

**Comment by anapnoe** [comment]
Hi Rule34 thank you for your support, you need both sd-webui-ux-dock and sd-webui-ux enabled
when webui-ux-dock starts you have to click on one of the layouts left buttons main menu bar, clicking the top one you can load modify and save your custom views, when you create a new view you need to restart the ui to show up, modify existing ones does no need any restart recommended Chrome or Firefox latest, if you still have an issue disable all non builtin extensions to test

this is with the latest forge 
for the networks go to Settings webui-ux and enable Event Delegation for Extra Networks
for notification I have never used it I always listen to music I will have a look and fix it with next release
 
![Untitled](https://github.com/user-attachments/assets/90b78c93-c9e9-42c5-abaf-6153532aa6fe)

**Comment by kyle215ps3** [comment]
> Hi Rule34 thank you for your support, you need both sd-webui-ux-dock v2, unzip and put it in the extensions folder, and sd-webui-ux enabled when webui-ux-dock starts you have to click on one of the layouts left buttons main menu bar, clicking the top one you can load modify and save your custom views, by drag and drop the items on top, when you create a new view you need to restart the ui to show up, modify existing ones does no need any restart recommended Chrome or Firefox latest, if you still have an issue disable all non builtin extensions to test
> 
> this is with the latest forge for the networks go to Settings webui-ux and enable Event Delegation for Extra Networks for notification I have never used it I always listen to music I will have a look and fix it with next release
> 
> ![Untitled](https://private-user-images.githubusercontent.com/124302297/392608163-90b78c93-c9e9-42c5-abaf-6153532aa6fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjIyOTIsIm5iZiI6MTczMzM2MTk5MiwicGF0aCI6Ii8xMjQzMDIyOTcvMzkyNjA4MTYzLTkwYjc4YzkzLWM5ZTktNDJjNS1hYmFmLTYxNTM1MzJhYTZmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwMTI2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODNiZTE2NDBkZjBmMzUyNjNjNTg4NDMyNWY1YmE0NWVlODRiN2VhOWE5ZTM5MDRjY2ZjMGRmODYyNTJjZDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f-qA4PeGNViFMtQ22EHCWk8KDlg_s6IvEnt99IYtxs4)

Awesome! Thank you!! It works on getting the workspace, I tested on a fresh forge install and it most likely was a non built in extension.
So I'll be doing this on my main UI.

I absolutly love the UI you have created, I remember quite a while back and finding it and I couldn't afford to spend money yet but was dying to get it haha.
Thank you sooo much for making this amazing UI keep up the amazing work :D

and awesome I use the notification since I schedule batches to be made in the background and sometimes I need a normal generation and I tend to forget to check back while I'm doing something else haha :D
