### ISSUE TITLE
Conflict Between Stable Diffusion WebUI Localization (zh_Hant) and Txt2Image Results: Output Size Too Small in Forge

### ISSUE THREAD

**Issue by yamasoo** [anapnoe/sd-webui-ux#4]
webui-forge
txt2image results too small
 how can fix this?

![image](https://github.com/user-attachments/assets/2af2e0b3-929c-4946-b2e8-b43d7553fa52)

**Comment by anapnoe** [comment]
Here are a few suggestions you can try: Use Chrome and disable your extensions. Then, enable them one by one to identify which one is causing the issue. Once you've pinpointed the culprit, please revisit the issue and rename the title to be more descriptive.

**Comment by yamasoo** [comment]
Find out what cause it 
if localization select  none is ok select hant will cause it
![image](https://github.com/user-attachments/assets/88fa3d02-1f3c-4c15-b6f4-fa434f708f76)

![image](https://github.com/user-attachments/assets/a8a282cc-022d-4fb5-bb41-4ff7a0f575c3)

https://github.com/bluelovers/stable-diffusion-webui-localization-zh_Hant

**Comment by anapnoe** [comment]
To resolve the issue, please update your JSON localization file by modifying the key-value pairs as follows:

Replace:
`"Version:": "版本: ",
"version:": "版本: ",

With:`
`"Version:": "Version",
"version:": "version: ",`

This change should address the problem. However, please test it to ensure that everything works as expected.

**Comment by yamasoo** [comment]
it WORKs thanks 
![image](https://github.com/user-attachments/assets/47f5b4ee-70fa-4ae2-a76d-b0f55461c732)
