### ISSUE TITLE
[Bug and Feature Request] Styles and lora metadata editor goes black and extension support

### ISSUE THREAD

**Issue by mjpr-3435** [anapnoe/sd-webui-ux#5]
First of all, the UI design is great, it's very user friendly, nice job.

Bug: When I try to open the styles or lora metadata editors, the screen goes black and if I hover over it I get a 'Popup' caption.

Features Request:

- There is an extension that adds an 'X' button to the window where the generated image appears, basically to delete the image if you are not interested. It would be very convenient if the 'X' could be displayed in this UI.
https://github.com/AlUlkesh/sd_delete_button

- There is another extension that allows you to create a queue for tasks, currently the main version does not run on forge, I use this fork https://github.com/supersonic13/sd-webui-agent-scheduler
This extension adds a button below the generate button, but in this UI, it does not appear, it gives quite a few facilities and it would be nice to have its functionality implemented in some way.

**Comment by anapnoe** [comment]
Thank you for your kind words about the UI design; I’m glad you find it user-friendly!

Regarding the issue you mentioned, it’s important to note that I only allow one issue to be posted at a time to help keep things organized and manageable. This way, I can focus on resolving each issue individually.

While I appreciate your feature requests, it would be best to submit those separately as well, as this helps in tracking and addressing them more effectively.

Thanks again for the feedback
